# Generated by Django 3.0 on 2019-12-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0005_auto_20191219_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ns101',
            old_name='19-12-31',
            new_name='Y19M12D31',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='20-01-01',
            new_name='Y20M01D01',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='20-01-02',
            new_name='Y20M01D02',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='20-01-03',
            new_name='Y20M01D03',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='20-01-04',
            new_name='Y20M01D04',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='20-01-05',
            new_name='Y20M01D05',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='20-01-06',
            new_name='Y20M01D06',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='20-01-07',
            new_name='Y20M01D07',
        ),
    ]
