# Generated by Django 3.0 on 2019-12-31 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0006_auto_20191231_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ns101',
            old_name='Y19M12D31',
            new_name='D01M01Y20',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='Y20M01D01',
            new_name='D02M01Y20',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='Y20M01D02',
            new_name='D03M01Y20',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='Y20M01D03',
            new_name='D04M01Y20',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='Y20M01D04',
            new_name='D05M01Y20',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='Y20M01D05',
            new_name='D06M01Y20',
        ),
        migrations.RenameField(
            model_name='ns101',
            old_name='Y20M01D06',
            new_name='D07M01Y20',
        ),
        migrations.RemoveField(
            model_name='ns101',
            name='Y20M01D07',
        ),
    ]
