# Generated by Django 3.0 on 2020-01-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0010_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
