# Generated by Django 3.0 on 2020-01-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
