# Generated by Django 3.0 on 2020-02-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_shot',
            field=models.ImageField(blank=True, upload_to='test_images'),
        ),
    ]
